[package]
name = "self-healing-encryption"
version = "0.1.0"
edition = "2025"
description = "An advanced self-healing encryption system implemented in Rust."
license = "MIT"

[dependencies]
rand = "0.8"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sha2 = "0.10"
log = "0.4"
simplelog = "0.12"
chrono = { version = "0.4", features = ["serde"] }
base64 = "0.13"
hex = "0.4"
